### ISSUE TITLE
Integration seems broken today

### ISSUE THREAD

**Issue by Gilles2senior** [fars-fede-fire/volvoaaos#71]
### System Health details

Enregistreur: homeassistant.config_entries
Source: config_entries.py:594
S'est produit pour la première fois: 21:26:20 (2 occurrences)
Dernier enregistrement: 21:31:47

Error setting up entry Volvo - XC90 Gilles 2024 for volvoaaos
Traceback (most recent call last):
  File "/config/custom_components/volvoaaos/volvo.py", line 41, in _request
    response = await self.session.request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/aiohttp/client.py", line 686, in _request
    await resp.start(conn)
  File "/root/.local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1022, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/aiohttp/streams.py", line 643, in read
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/volvoaaos/__init__.py", line 47, in async_setup_entry
    connected_vehicle_door_status_data = await connected_vehicle.get_door_status()
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/volvoaaos/volvo.py", line 197, in get_door_status
    response = await self._request(url=url, headers=headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/volvoaaos/volvo.py", line 40, in _request
    async with async_timeout.timeout(self.request_timeout):
  File "/usr/local/lib/python3.12/site-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.12/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
TimeoutError

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

Erreur "Echec de la configuration" sur l'intégration Volovo AAOS.
Tried to reloadn, and same error. Was working well a couple of days ago. Noticed failure today.

### Reproduction steps

Ststus in "Parameters" of HA.
All entities being "Unavailable" 

### Debug logs

```text
Enregistreur: homeassistant.config_entries
Source: config_entries.py:594
S'est produit pour la première fois: 21:26:20 (2 occurrences)
Dernier enregistrement: 21:31:47

Error setting up entry Volvo - XC90 Gilles 2024 for volvoaaos
Traceback (most recent call last):
  File "/config/custom_components/volvoaaos/volvo.py", line 41, in _request
    response = await self.session.request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/aiohttp/client.py", line 686, in _request
    await resp.start(conn)
  File "/root/.local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1022, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/aiohttp/streams.py", line 643, in read
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/volvoaaos/__init__.py", line 47, in async_setup_entry
    connected_vehicle_door_status_data = await connected_vehicle.get_door_status()
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/volvoaaos/volvo.py", line 197, in get_door_status
    response = await self._request(url=url, headers=headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/volvoaaos/volvo.py", line 40, in _request
    async with async_timeout.timeout(self.request_timeout):
  File "/usr/local/lib/python3.12/site-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.12/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
TimeoutError
```

**Comment by andynash** [comment]
I don't yet use this integration or the MQTT add-on, instead I use a bespoke REST configuration within Home Asssitant that I set up before either existed.

However I think my experience may be relevant to this issue.

My set-up hasn't been working for a week or so, and I found this issue for the volvo2mqtt add-on created by @dielee that suggests Volvo now enforce the OTP method of authorisation - perhaps this is affecting the OP for that issue (who uses NodeRed), myself (using REST) and this integration too?

https://github.com/Dielee/volvo2mqtt/issues/245

Of course it would be nice if Volvo could actually communicate this major change in some way to API users but communication clearly isn't their strong point 😁

I did try to get OTP working in Postman some time ago when I thought this was the cause of a problem (it turned out to be something else), so I guess I'll need to take a look at that again - I can't remember if I got things working or not - and transpose that into my REST process somehow. 

I'd like to use this integration but moving will be a lot of work (I'd have moved already but my set-up was working just fine), and if I'm right it sounds as though this integration won't work either unless OTP support is added?

Can anyone confirm this integration is still working for them? If I'm right it probably isn't.
